# This workflow will build a Python app using Poetry, generate requirements.txt,
# prepare a staging directory with the correct structure, and deploy it to an
# Azure Functions App on Linux when a new release is published.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-configuration
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#    - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Ensure your pyproject.toml file is correctly configured for your project.
#    You may still want to keep poetry-plugin-export in [tool.poetry.requires-plugins]
#    for local development consistency, but this workflow will install it explicitly.
# 3. Change env variables for your configuration.

name: Deploy Python project to Azure Function App on Release

# Trigger the workflow when a new release is published
on:
  release:
    types: [published]

env:
  AZURE_FUNCTIONAPP_NAME: 'tvbingefriendshows'    # set this to your function app name on Azure
  # AZURE_FUNCTIONAPP_PACKAGE_PATH is no longer directly used for deployment path,
  # as we now use a 'staging' directory. It's kept for potential other uses or context.
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'                     # set this to the python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev # Or your target environment
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry and Export Plugin
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry --version # Output poetry version for debugging
        echo "Attempting to install poetry-plugin-export using 'poetry self add'..."
        poetry self add poetry-plugin-export
        echo "Listing Poetry plugins:"
        poetry plugin show --verbose # List installed plugins to verify (added --verbose)

    - name: Prepare Staging Directory for Deployment
      shell: bash
      run: |
        echo "Current directory before staging: $(pwd)"
        ls -la

        echo "Generating requirements.txt using Poetry..."
        poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev
        
        if [ ! -f requirements.txt ]; then
          echo "ERROR: requirements.txt not found after poetry export!"
          echo "Poetry version: $(poetry --version)"
          echo "Poetry plugins found:"
          poetry plugin show --verbose || echo "Failed to list poetry plugins"
          exit 1
        fi
        echo "Successfully generated requirements.txt."
        cat requirements.txt # Display contents for verification

        echo "Creating staging directory..."
        mkdir -p staging

        echo "Copying root application files (function_app.py, host.json) to staging/ ..."
        cp function_app.py staging/
        cp host.json staging/
        cp .funcignore staging/

        echo "Copying contents of src/ to staging/ ..."
        if [ -d "src" ]; then
          cp -a src/* staging/
        else
          echo "Warning: 'src' directory not found at $(pwd)/src"
        fi
        
        echo "Installing dependencies into staging/.python_packages..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target="staging/.python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages"

        echo "-------------------------------------"
        echo "Contents of staging directory:"
        ls -laR staging # List contents of staging recursively
        echo "-------------------------------------"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: staging # Deploy the staging directory
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        # Set scm-do-build-during-deployment to false as we are providing a complete package
        # with all dependencies in .python_packages.
        scm-do-build-during-deployment: false
        # enable-oryx-build is not needed and ignored when scm-do-build-during-deployment is false.
